### ISSUE TITLE
CleverSpa.Sensor error

### ISSUE THREAD

**Issue by AlexGreenUK** [Wh1terat/cleverspa-component#1]
Error on start up

![Configuration - ](https://user-images.githubusercontent.com/845591/131428270-a472520c-e93d-4a14-bd9a-e3ef7735fdca.png)

**Comment by Wh1terat** [comment]
It's in all the docs but not in the stable branch yet.

I thought I had caught that... 

```python
# STATE_CLASS_TOTAL_INCREASING only added recently.
try:
    from homeassistant.components.sensor import STATE_CLASS_TOTAL_INCREASING
except ModuleNotFoundError as err:
    STATE_CLASS_TOTAL_INCREASING = None
```

**Comment by Wh1terat** [comment]
Disabled completely in dcfd44bd41f1e70d800e9143d5f8e31c1b013bb6.
