### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by atmezferix** [Wh1terat/cleverspa-component#4]
Hi,

Very please to have found this component and has been working fine.  However its recently stopped with the error "Failed to setup:None "von the integrations page.  I've recently upgraded to 2021.11.3 not sure exactly when it broke or it it is related to that version or something else.

**Comment by Wh1terat** [comment]
Hi @atmezferix,

Hmm. Odd, not seen that issue myself.

Could you try removing the integration and re-adding and see if it persists?

Thanks.

**Comment by atmezferix** [comment]
Hi @Wh1terat,

Thanks for coming back to me.  Removed the integration and re-added all working... wish I'd tried that earlier :-)

Thanks again..

**Comment by Wh1terat** [comment]
That’s great to hear 😁
Glad my integration is of use to you!
