### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alastairg100** [Wh1terat/cleverspa-component#7]
Hi. When I try to install the program as an integration, it comes up with the below error

Config flow could not be loaded: {"message":"Invalid handler specified"}

Is there a way to get around this? I have tried to reinstall the custom integration through HACS but it again occurred. I'm new to this to simple answers only!
Thanks

**Comment by vinniegraves** [comment]
Hi All
Having the same issue as Alastairg100, any ideas ?

Many Thanks

Vince

**Comment by JamesTingle** [comment]
Hi. I too get this error.

The log from Ha gives a bit more detail:

Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 07:00:46 (1 occurrences)
Last logged: 07:00:46

Error occurred loading flow for integration cleverspa: cannot import name 'gaecontrib' from 'requests_toolbelt._compat' (/usr/local/lib/python3.10/site-packages/requests_toolbelt/_compat.py)



I did find this recent post online:

https://stackoverflow.com/questions/76208396/pyrebase4-error-cannot-import-name-gaecontrib

It looks like maybe it's a problem elsewhere. I don't have a clue how to work around it, however.

**Comment by markbooker** [comment]
Has anyone had any joy with fixing the issue or is this now a dead topic as cleverspa are no longer?

**Comment by drxjan** [comment]
no luck fixing the issue. I have the feeling it has to do with the firebase authentication part, but I don't really understand how that works @Wh1terat any chance you could give us a hand? Thank you

**Comment by kaotix** [comment]
I hate to hijack this but if you check my profile my implementation of this should be working with the latest version. The owner of this repo hasn't maintained this since this breaking change.

**Comment by drxjan** [comment]
Hi @kaotix, thank you so much for your message and pardon my ignorance, I did not see that you re-implemented this. I just managed to install it and it works like a charm. Thank you so much!!

**Comment by kaotix** [comment]
@drxjan no problem at all, glad my code could help out. I've had plenty of help to make it function so I'm happy it works for you.

**Comment by Wh1terat** [comment]
Ah yeah sorry guys, I don't even own a cleverspa anymore - I'll set the repo to readonly/archived state.

@kaotix still think you should be using the water heater entity 😝
